n = float(input('Digite a área aferida em metros: '))
km = (n / 1000)
hm = (n / 100)
dam = (n / 10)
dm = (n * 10)
cm = (n * 100)
mm = (n * 1000)
print('Area em km {}. Em hm {}. Em dam {}. Em dm {}. Em cm {}. Em mm {}.'.format(km, hm, dam, dm, cm, mm))
